version: '3.4'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  auctionservice:
    image: ${DOCKER_REGISTRY-}auctionservice
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile

volumes:
  pgdata:

